### ISSUE TITLE
Weird console bugs

### ISSUE THREAD

**Issue by Tobberz** [EpicQuestz/EpicSuite#7]
I think this is EpicSuite

![image](https://user-images.githubusercontent.com/34923362/97216217-68d55000-17bd-11eb-9429-c555aaa3fd2a.png)

https://pastebin.com/vi67LYBU

**Comment by StealWonders** [comment]
Not actually an issue, just debug prints as the version on the server is the latest development build. Will be fixed in the future :-)
Closing and marking as invalid.
